# Generated by Django 3.1.4 on 2020-12-15 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_auto_20201215_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveyinfo',
            name='token',
            field=models.CharField(default='token', max_length=255),
            preserve_default=False,
        ),
    ]
